// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
var fs = require('fs');
var path = require('path');

module.exports = function(app){
//    require('./health')(app);
//    console.log(app)

    var handlers = [];

    var files = fs.readdirSync(__dirname);
    files.forEach(function(fileName) {
      if (fileName != '__index.js') { 
        var file = path.join(__dirname, fileName);
        require(file)(app);
      }
    });
    
}; 
